language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - mysql
  - postgresql
env:
  - DJANGO=1.11 DB=sqlite
  - DJANGO=1.11 DB=mysql
  - DJANGO=1.11 DB=postgres
  - DJANGO=2.2 DB=sqlite
  - DJANGO=2.2 DB=mysql
  - DJANGO=2.2 DB=postgres
  - DJANGO=3.0b1 DB=sqlite
  - DJANGO=3.0b1 DB=mysql
  - DJANGO=3.0b1 DB=postgres
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=2.2 DB=mysql
    - python: "2.7"
      env: DJANGO=2.2 DB=postgres
    - python: "2.7"
      env: DJANGO=2.2 DB=sqlite
    - python: "2.7"
      env: DJANGO=3.0b1 DB=mysql
    - python: "2.7"
      env: DJANGO=3.0b1 DB=postgres
    - python: "2.7"
      env: DJANGO=3.0b1 DB=sqlite

    - python: "3.5"
      env: DJANGO=1.11 DB=mysql
    - python: "3.5"
      env: DJANGO=1.11 DB=postgres
    - python: "3.5"
      env: DJANGO=1.11 DB=sqlite
    - python: "3.5"
      env: DJANGO=3.0b1 DB=mysql
    - python: "3.5"
      env: DJANGO=3.0b1 DB=postgres
    - python: "3.5"
      env: DJANGO=3.0b1 DB=sqlite
      
    - python: "3.6"
      env: DJANGO=1.11 DB=mysql
    - python: "3.6"
      env: DJANGO=1.11 DB=postgres
    - python: "3.6"
      env: DJANGO=1.11 DB=sqlite

    - python: "3.7"
      env: DJANGO=1.11 DB=mysql
    - python: "3.7"
      env: DJANGO=1.11 DB=postgres
    - python: "3.7"
      env: DJANGO=1.11 DB=sqlite

    - python: "3.8"
      env: DJANGO=1.11 DB=mysql
    - python: "3.8"
      env: DJANGO=1.11 DB=postgres
    - python: "3.8"
      env: DJANGO=1.11 DB=sqlite

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'create database sqlutil;'; fi
  - if [[ "$DB" == "postgres" ]]; then psql -c 'create database sqlutil;' -U postgres; fi
install:
  - pip install pip --upgrade
  - if [[ "$DB" == "mysql" && "$DJANGO" == "1.11" ]]; then pip install mysqlclient\<=1.3.13; fi
  - if [[ "$DB" == "mysql" && "$DJANGO" == "2.2" ]]; then pip install mysqlclient; fi
  - if [[ "$DB" == "mysql" && "$DJANGO" == "3.0b1" ]]; then pip install mysqlclient; fi
  - if [[ "$DB" == "postgres" ]]; then pip install psycopg2; fi
  - pip install -q Django==$DJANGO
script:
  - python runtests.py --settings=sql_util.tests.test_"$DB"_settings
